(custom-set-variables
 '(auto-save-default nil)
 '(browse-url-browser-function (quote browse-url-netscape))
 '(complex-buffers-menu-p nil)
 '(default-toolbar-position (quote right))
 '(font-lock-mode t nil (font-lock))
 '(gutter-buffers-tab-visible-p nil)
 '(init-face-from-resources nil)
 '(next-line-add-newlines t)
 '(query-user-mail-address nil)
 '(toolbar-mail-commands-alist (quote ((not-configured . toolbar-not-configured) (vm . vm) (gnus . gnus-no-server) (mh . mh-rmail) (exmh toolbar-external "exmh"))))
 '(toolbar-mail-reader (quote vm))
 '(toolbar-news-commands-alist (quote ((gnus . toolbar-gnus))))
 '(toolbar-news-reader (quote gnus))
 '(toolbar-visible-p t)
 '(user-mail-address "rjray@blackperl.com"))
(custom-set-faces
 '(default ((t (:foreground "gold2" :background "NavyBlue" :size "10pt" :family "Courier 10 Pitch"))) t)
 '(bold ((t (:bold t))) t)
 '(bold-italic ((t (:bold t :italic t))) t)
 '(cperl-array-face ((((class color) (background dark)) (:foreground "yellow"))))
 '(cperl-hash-face ((((class color) (background dark)) (:foreground "red2"))))
 '(custom-button-face ((t (:bold t))))
 '(custom-comment-face ((((class grayscale color) (background light)) (:foreground "red" :background "gray85"))))
 '(custom-comment-tag-face ((((class color) (background light)) nil)))
 '(custom-face-tag-face ((t (:bold t))))
 '(custom-group-tag-face ((((class color) (background light)) (:foreground "lightblue" :underline t))))
 '(custom-invalid-face ((((class color)) (:foreground "yellow" :background "red"))))
 '(custom-state-face ((((class color) (background light)) (:foreground "gold2"))))
 '(custom-variable-button-face ((t (:bold t))))
 '(custom-variable-tag-face ((((class color) (background light)) (:foreground "cyan" :underline t))))
 '(cvs-filename-face ((((class color) (background light)) (:foreground "cadetblue"))))
 '(cvs-header-face ((((class color) (background light)) (:foreground "cadetblue" :bold t))))
 '(cvs-msg-face ((t (:italic t))))
 '(develock-long-line-face-1 ((t nil)))
 '(develock-long-line-face-2 ((t nil)))
 '(develock-whitespace-1 ((t (:underline nil))))
 '(develock-whitespace-3 ((t nil)))
 '(develock-whitespace-face-1 ((t (:underline t))))
 '(develock-whitespace-face-3 ((t nil)))
 '(diff-file-header-face ((((class color) (background dark)) (:background "grey60" :bold t))))
 '(diff-index-face ((((class color) (background dark)) (:background "grey60" :bold t))))
 '(dired-face-directory ((((type x pm mswindows tty) (class color)) (:bold t))))
 '(fg:black ((t (:foreground "black"))) t)
 '(font-lock-comment-face ((nil (:foreground "antiquewhite" :italic t))))
 '(font-lock-constant-face ((t (:foreground "steelblue1"))))
 '(font-lock-doc-string-face ((nil (:foreground "lightgreen"))))
 '(font-lock-emphasized-face ((t (:foreground "blue" :background "lightyellow2"))) t)
 '(font-lock-function-name-face ((nil (:foreground "salmon"))))
 '(font-lock-keyword-face ((nil (:foreground "lightblue"))))
 '(font-lock-other-emphasized-face ((t (:foreground "blue" :background "gray75"))) t)
 '(font-lock-other-type-face ((t (:foreground "tan"))) t)
 '(font-lock-preprocessor-face ((nil (:foreground "cadetblue3"))))
 '(font-lock-string-face ((nil (:foreground "green2"))))
 '(font-lock-type-face ((nil (:foreground "wheat"))))
 '(font-lock-variable-name-face ((nil (:foreground "goldenrod" :italic t))))
 '(font-lock-warning-face ((nil (:foreground "black" :background "white" :bold t))))
 '(gnus-summary-high-ticked-face ((((class color) (background dark)) (:bold t)) (((class color) (background light)) (:bold t :foreground "firebrick")) (t (:bold t))))
 '(gnus-summary-low-ticked-face ((((class color) (background dark)) (:italic t)) (((class color) (background light)) (:italic t :foreground "firebrick")) (t (:italic t))))
 '(gnus-summary-selected-face ((t (:bold t))))
 '(highlight ((t (:foreground "red" :background "darkseagreen2"))) t)
 '(html-helper-bold-face ((t (:bold t))))
 '(html-helper-italic-face ((t (:italic t))))
 '(hyper-apropos-documentation ((((class color) (background light)) (:foreground "green2"))))
 '(hyper-apropos-heading ((t (:bold t))))
 '(hyper-apropos-hyperlink ((((class color) (background light)) (:foreground "pink"))))
 '(isearch ((t (:inverse-video t))) t)
 '(italic ((t (:italic t))) t)
 '(message-cited-text-face ((((class color) (background dark)) (:italic t :foreground "cyan2")) (((class color) (background light)) (:foreground "red")) (t (:bold t))))
 '(message-header-name-face ((((class color) (background dark)) (:foreground "cyan")) (((class color) (background light)) (:foreground "cornflower blue")) (t (:bold t))))
 '(message-header-other-face ((((class color) (background dark)) (:italic t :foreground "pink")) (((class color) (background light)) (:foreground "steel blue")) (t (:bold t :italic t))))
 '(message-header-xheader-face ((((class color) (background dark)) (:foreground "gray90")) (((class color) (background light)) (:foreground "blue")) (t (:bold t))))
 '(message-separator-face ((((class color) (background dark)) (:foreground "lightblue")) (((class color) (background light)) (:foreground "brown")) (t (:bold t))))
 '(modeline ((t (:foreground "black" :background "gray75"))) t)
 '(modeline-buffer-id ((t (:foreground "NavyBlue" :background "gray75"))) t)
 '(modeline-mousable ((t (:foreground "gray20" :background "gray75" :bold t))) t)
 '(modeline-mousable-minor-mode ((t (:foreground "red" :background "gray75"))) t)
 '(text-cursor ((t (:foreground "navyblue" :background "red"))) t)
 '(widget-button-pressed-face ((((class color)) (:foreground "red")))))
